/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2016-10-03 15:28:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.Htmlpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class htmlcolor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"css/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/w3-theme-black.css\">   \r\n");
      out.write("<div class=\" w3-card-2 w3-round\">\r\n");
      out.write("<div class=\"w3-third w3-black\">\r\n");
      out.write("<h2>On Black</h2>\r\n");
      out.write("<p class=\"w3-text-red\">w3-text-red</p>\r\n");
      out.write("<p class=\"w3-text-pink\">w3-text-pink</p>\r\n");
      out.write("<p class=\"w3-text-purple\">w3-text-purple</p>\r\n");
      out.write("<p class=\"w3-text-deep-purple\">w3-text-deep-purple</p>\r\n");
      out.write("<p class=\"w3-text-indigo\">w3-text-indigo</p>\r\n");
      out.write("<p class=\"w3-text-blue\">w3-text-blue</p>\r\n");
      out.write("<p class=\"w3-text-light-blue\">w3-text-light-blue</p>\r\n");
      out.write("<p class=\"w3-text-cyan\">w3-text-cyan</p>\r\n");
      out.write("<p class=\"w3-text-aqua\">w3-text-aqua</p>\r\n");
      out.write("<p class=\"w3-text-teal\">w3-text-teal</p>\r\n");
      out.write("<p class=\"w3-text-green\">w3-text-green</p>\r\n");
      out.write("<p class=\"w3-text-light-green\">w3-text-light-green</p>\r\n");
      out.write("<p class=\"w3-text-lime\">w3-text-lime</p>\r\n");
      out.write("<p class=\"w3-text-sand\">w3-text-sand</p>\r\n");
      out.write("<p class=\"w3-text-khaki\">w3-text-khaki</p>\r\n");
      out.write("<p class=\"w3-text-yellow\">w3-text-yellow</p>\r\n");
      out.write("<p class=\"w3-text-amber\">w3-text-amber</p>\r\n");
      out.write("<p class=\"w3-text-orange\">w3-text-orange</p>\r\n");
      out.write("<p class=\"w3-text-deep-orange\">w3-text-deep-orange</p>\r\n");
      out.write("<p class=\"w3-text-blue-grey\">w3-text-blue-grey</p>\r\n");
      out.write("<p class=\"w3-text-brown\">w3-text-brown</p>\r\n");
      out.write("<p class=\"w3-text-light-grey\">w3-text-light-grey</p>\r\n");
      out.write("<p class=\"w3-text-grey\">w3-text-grey</p>\r\n");
      out.write("<p class=\"w3-text-dark-grey\">w3-text-dark-grey</p>\r\n");
      out.write("<p class=\"w3-text-black\">w3-text-black</p>\r\n");
      out.write("<p class=\"w3-text-white\">w3-text-white</p>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
